# TODO: Finish

# Base image with Azure-Cli
FROM mcr.microsoft.com/azure-cli:latest

# Install DevOps extension for Azure Cli (az devops)
RUN az extension add --name azure-devops

# Install Bash, Curl, Git, Nano & Bash completion
RUN apk update && \
    apk upgrade && \
    apk add bash curl git nano bash-completion && \
    echo "source /etc/bash_completion" >> ~/.bashrc

# Install PowerShell Core
RUN apk add --no-cache ca-certificates less ncurses-terminfo-base krb5-libs libgcc libintl libssl1.1 libstdc++ tzdata userspace-rcu zlib icu-libs curl && \
    apk -X https://dl-cdn.alpinelinux.org/alpine/edge/main add --no-cache lttng-ust && \
    curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.4/powershell-7.0.0-preview.4-linux-alpine-x64.tar.gz -o /tmp/powershell.tar.gz && \
    mkdir -p /opt/microsoft/powershell/7-preview && \
    tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7-preview && \
    chmod +x /opt/microsoft/powershell/7-preview/pwsh && \
    ln -s /opt/microsoft/powershell/7-preview/pwsh /usr/bin/pwsh
 
# Install Kubernetes-Cli (kubectl), and completion
RUN az aks install-cli && \
    kubectl completion bash > /usr/share/bash-completion/completions/kubectl_completions.sh

# Install Helm-Cli (helm), and completion
RUN curl -LO https://git.io/get_helm.sh && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh && \
    helm init --client-only && \
    helm repo update && \
    helm completion bash > /usr/share/bash-completion/completions/helm_completions.sh

# Install Helm-Cli version 3 (helm3)
# Install 2to3 plugin for Helm-Cli version 3 (helm3 2to3)
RUN curl -LO https://get.helm.sh/helm-v3.0.2-linux-amd64.tar.gz && \
    mkdir helm3 && \
    tar -xzf helm-v3.0.2-linux-amd64.tar.gz --directory helm3 && \
    ln -s /helm3/linux-amd64/helm /usr/bin/helm3 && \
    rm helm-v3.0.2-linux-amd64.tar.gz && \
    helm3 plugin install https://github.com/helm/helm-2to3

# Install Powershell modules
RUN pwsh -c "Install-Module PS-Menu -Force" && \
    pwsh -c "Install-Module -Name PSBashCompletions -Scope CurrentUser -Force"

# # Slim down image
# RUN apt-get clean && \
#     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/man/?? /usr/share/man/??_*

WORKDIR /app
ENTRYPOINT ["bash"]