controller:
  admissionWebhooks:
    patch:
      nodeSelector:
        "kubernetes.io/os": linux
  nodeSelector:
    "kubernetes.io/os": linux
  kind: DaemonSet 
  service:
    externalTrafficPolicy: "Local"
defaultBackend:
  nodeSelector:
    "kubernetes.io/os": linux