apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prometheus-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: communicate-prometheus@3shape.com
    privateKeySecretRef:
      name: prometheus-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress-trafficmanager
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: prometheus-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 79.171.146.0/26, 185.147.72.0/26, 195.49.232.0/22, 217.66.102.249/28, 212.90.183.32/29
spec:
  tls:
  - hosts:
    - ${{ClusterName}}-prometheus.trafficmanager.net
    secretName: prometheus-certificate-trafficmanager
  rules:
  - host: ${{ClusterName}}-prometheus.trafficmanager.net
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: prometheus-server
            port:
              number: 80