controller:
  config:
    # ## proxy-read-timeout: "1800"
    # ## proxy-send-timeout: "1800"
    # ## client-body-buffer-size: 16m
    # ## proxy-body-size: 1024m 

    # ssl-session-timeout: "100m"
    # proxy-protocol-header-timeout: "20s"
    # upstream-keepalive-timeout: "240"
    # proxy-next-upstream-timeout: "1800"
    # client-header-buffer-size: "1m"
    # client-body-buffer-size: "16m"
    # client-body-timeout: "1800"
    # client-header-timeout: "1800"
    # proxy-body-size: "512m"
    # proxy-buffer-size: "4m"
    # proxy-connect-timeout: "50"
    # proxy-read-timeout: "1800"
    # proxy-send-timeout: "1800"
    # proxy-stream-timeout: "6000s"
    # ssl-buffer-size: "4m"

    # proxy_connect_timeout: "300"
    # proxy_send_timeout: "300"
    # proxy_read_timeout: "300"

    # http2-max-field-size: "4m"
    # http2-max-header-size: "16m"
    # http2-max-requests: "10000"
    # http2-max-concurrent-streams: "10000"
    # large-client-header-buffers: "40 8m"
  service:
    externalTrafficPolicy: "Local"
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: 30