name: Docker Image CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: bo0petersen
        password: ${{ secrets.DOCKER_HUB_PAT }}
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag bo0petersen/aks-cli:$(date +%s)
        docker build . --file Dockerfile --tag bo0petersen/aks-cli:latest
    
    - name: Docker Push
      run: |
        docker push bo0petersen/aks-cli:$(date +%s)
        docker push bo0petersen/aks-cli:latest
